fix: Send environment variable as a function argument

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,19 +1,22 @@
 #!/usr/bin/env bash
 
 maintenance(){
-[ $1 == on ] && status=true || status=false
+status=$1; shift
+auth_key=$2; shift
+[ "$status" == on ] && status=true || status=false
 curl -n -X PATCH https://api.heroku.com/apps/mighty-mesa-44488 \
   -d "{ \"maintenance\": $status}" \
   -H "Content-Type: application/json" \
   -H "Accept: application/vnd.heroku+json; version=3" \
-  -H "Authorization: Bearer {$api_oauth}"
+  -H "Authorization: Bearer {$auth_key}"
 }
 
 echo "I've been run during release!!!"
 echo "Below there are environment variables:"
 env
+[ -z "$api_oauth" ] && echo "[Error]: OAuth variable wasn't set" && exit 1
 echo "Starting some long process..."
-maintenance on
+maintenance on "$api_oauth"
 echo "Enabing maintenance mode"
 echo "Waiting till 10..."
 for i in {1..10}
@@ -21,7 +24,7 @@ do
 	sleep 5s
 	echo -n "$i."
 done
-maintenance off
+maintenance off "$api_oauth"
 echo "Maintenance mode has disabled"
 echo
 echo "All done. We gonna go forward..."
